apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api-key
  namespace: datadog
  annotations:
    argocd.argoproj.io/sync-wave: "43"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: lab-k8s-store
  target:
    name: datadog-api-key
    creationPolicy: Owner
  data:
  - secretKey: api-key
    remoteRef:
      key: datadog-api-key-src
      property: api-key

