apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-apps
  namespace: platform-system
spec:
  project: default
  source:
    repoURL: https://github.com/dthiyaga/gitops
    targetRevision: main
    path: registry
    directory:
      recurse: true
  destination:
    namespace: registry
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
