apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-ca
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  isCA: true
  commonName: local-ca
  secretName: local-ca-key-pair
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: local-ca
  annotations:
    argocd.argoproj.io/sync-wave: "23"
spec:
  ca:
    secretName: local-ca-key-pair

